/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/FiaS26cBZz0
 */
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { DropdownMenuTrigger, DropdownMenuItem, DropdownMenuContent, DropdownMenu } from "@/components/ui/dropdown-menu"

export function HomePage() {
  return (
    (<header
      className="flex items-center justify-between px-6 py-4 bg-white dark:bg-gray-800">
      <Link className="flex items-center" href="#">
        <FlagIcon className="w-8 h-8" />
        <h1 className="ml-2 text-lg font-semibold text-gray-700 dark:text-gray-200">Company Name</h1>
      </Link>
      <div className="flex items-center">
        <form className="flex items-center mr-6">
          <SearchIcon className="w-4 h-4 text-gray-700 dark:text-gray-200" />
          <input
            className="ml-2 bg-lightgray rounded-full focus:outline-none text-gray-700 dark:text-gray-200"
            placeholder="Search"
            type="text" />
        </form>
        <DropdownMenu className="rouded-lg">
          <DropdownMenuTrigger asChild>
            <Button variant="outline">Country</Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent>
            <DropdownMenuItem>USA</DropdownMenuItem>
            <DropdownMenuItem>UK</DropdownMenuItem>
            <DropdownMenuItem>Germany</DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button variant="outline">Language</Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent>
            <DropdownMenuItem>English</DropdownMenuItem>
            <DropdownMenuItem>German</DropdownMenuItem>
            <DropdownMenuItem>Spanish</DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
        <Button className="mx-4">Sign In</Button>
        <input className="form-checkbox text-blue-500 h-5 w-5" type="checkbox" />
        <span className="ml-2 text-gray-700 dark:text-gray-200">Dark Mode</span>
      </div>
    </header>)
  );
}


function FlagIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z" />
      <line x1="4" x2="4" y1="22" y2="15" />
    </svg>)
  );
}


function SearchIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>)
  );
}
