/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/OZ0dVMyAFmz
 */
import { SelectValue, SelectTrigger, SelectItem, SelectGroup, SelectContent, Select } from "@/components/ui/select"
import { Button } from "@/components/ui/button"

export function locationSelection() {
  return (
    (<div key="1" className="flex w-full max-w-sm items-center space-x-2">
      <Select className="flex-grow">
        <SelectTrigger>
          <SelectValue placeholder="Select a city" />
        </SelectTrigger>
        <SelectContent>
          <SelectGroup>
            <SelectItem value="newyork">New York</SelectItem>
            <SelectItem value="losangeles">Los Angeles</SelectItem>
            <SelectItem value="chicago">Chicago</SelectItem>
            <SelectItem value="houston">Houston</SelectItem>
            <SelectItem value="phoenix">Phoenix</SelectItem>
          </SelectGroup>
        </SelectContent>
      </Select>
      <Button>Use Current Location</Button>
    </div>)
  );
}
