/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/paLKQcyvB6z
 */
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"

export function multiImage() {
  return (
    (<div key="1" className="grid gap-4 w-full max-w-2xl mx-auto">
      <form>
        <div className="grid gap-4">
          <div className="grid w-full max-w-sm items-center gap-1.5">
            <Label htmlFor="pictures">Upload Images</Label>
            <div
              className="p-2 border-2 border-blue-500 rounded-md bg-[#e0f0ff] flex items-center justify-center">
              <FileTypeIcon className="w-4 h-4" />
              <Input className="w-full h-[50px]" id="pictures" multiple type="file" />
            </div>
          </div>
          <div className="grid sm:grid-cols-2 gap-4 w-full max-w-2xl mx-auto">
            <Card className="flex flex-col items-center gap-2">
              <Avatar>
                <AvatarImage alt="Uploaded image 1" src="/placeholder.svg?height=100&width=100" />
                <AvatarFallback>Uploaded Image 1</AvatarFallback>
              </Avatar>
              <Button
                className="w-[240px] justify-around text-center font-normal"
                variant="outline">
                <TrashIcon className="w-4 h-4" />
                Remove Image
              </Button>
            </Card>
            <Card className="flex flex-col items-center gap-2">
              <Avatar>
                <AvatarImage alt="Uploaded image 2" src="/placeholder.svg?height=100&width=100" />
                <AvatarFallback>Uploaded Image 2</AvatarFallback>
              </Avatar>
              <Button
                className="w-[240px] justify-around text-center font-normal"
                variant="outline">
                <TrashIcon className="w-4 h-4" />
                Remove Image
              </Button>
            </Card>
          </div>
          <Button className="w-[240px] justify-around text-center font-normal">
            <PlaneIcon className="w-4 h-4" />
            Submit
          </Button>
        </div>
      </form>
    </div>)
  );
}


function FileTypeIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M14.5 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7.5L14.5 2z" />
      <polyline points="14 2 14 8 20 8" />
      <path d="M9 13v-1h6v1" />
      <path d="M11 18h2" />
      <path d="M12 12v6" />
    </svg>)
  );
}


function TrashIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M3 6h18" />
      <path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6" />
      <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2" />
    </svg>)
  );
}


function PlaneIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M17.8 19.2 16 11l3.5-3.5C21 6 21.5 4 21 3c-1-.5-3 0-4.5 1.5L13 8 4.8 6.2c-.5-.1-.9.1-1.1.5l-.3.5c-.2.5-.1 1 .3 1.3L9 12l-2 3H4l-1 1 3 2 2 3 1-1v-3l3-2 3.5 5.3c.3.4.8.5 1.3.3l.5-.2c.4-.3.6-.7.5-1.2z" />
    </svg>)
  );
}
