/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ukBKvff646B
 */
import { Avatar } from "@/components/ui/avatar"
import { CardHeader, CardContent, Card } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"

export function MyAdCard() {
  return (
    (<main className="container mx-auto px-4 py-8 space-y-8">
      <Card>
        <CardHeader>
          <Avatar
            alt="Brand Logo"
            className="w-12 h-12"
            src="/placeholder.svg?height=48&width=48" />
          <h2 className="text-xl font-bold ml-4">Brand Name</h2>
        </CardHeader>
        <CardContent>
          <img
            alt="Ad Image"
            className="w-full h-64 object-cover rounded-lg"
            height="256"
            src="/placeholder.svg"
            style={{
              aspectRatio: "256/256",
              objectFit: "cover",
            }}
            width="256" />
          <div className="mt-4 space-y-2">
            <h3 className="text-lg font-semibold">Model Name</h3>
            <p className="text-gray-500">
              This is a description of the car being advertised. It has various features and benefits.
            </p>
            <div className="grid grid-cols-2 gap-2">
              <Badge>Category</Badge>
              <Badge>Ad Type</Badge>
              <Badge>Year</Badge>
              <Badge>Car Type</Badge>
              <Badge>Car Status</Badge>
              <Badge>Transmission</Badge>
              <Badge>Fuel Type</Badge>
              <Badge>Meter Range</Badge>
            </div>
          </div>
        </CardContent>
        <div className="p-4 flex space-x-4">
          <Button className="w-1/2 flex justify-center items-center space-x-2">
            <PencilIcon className="w-4 h-4" />
            <span>Edit</span>
          </Button>
          <Button className="w-1/2 flex justify-center items-center space-x-2">
            <TrashIcon className="w-4 h-4" />
            <span>Delete</span>
          </Button>
        </div>
      </Card>
    </main>)
  );
}


function PencilIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M17 3a2.85 2.83 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5Z" />
      <path d="m15 5 4 4" />
    </svg>)
  );
}


function TrashIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M3 6h18" />
      <path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6" />
      <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2" />
    </svg>)
  );
}
