/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/22ZM1nOKnV1
 */
import { CardTitle, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import Link from "next/link"

export function SignIn() {
  return (
    (<div className="w-full min-h-screen lg:flex">
      <div
        className="lg:w-1/2 p-6 lg:p-10 bg-gradient-to-r from-[#FF3337] via-[#009A8F] to-[#F5F853] to-[#FFFFFF] lg:flex lg:items-center lg:justify-center">
        <div className="space-y-4 text-center lg:text-left">
          <img
            alt="Company Logo"
            className="mx-auto lg:mx-0 w-16 h-16"
            height="64"
            src="/placeholder.svg"
            style={{
              aspectRatio: "64/64",
              objectFit: "cover",
            }}
            width="64" />
          <h1 className="text-3xl lg:text-4xl font-bold text-white">Company Name</h1>
          <p className="text-lg text-white opacity-80">Company Slogan</p>
        </div>
      </div>
      <div className="lg:w-1/2 p-6 lg:p-10 flex items-center justify-center">
        <Card className="max-w-lg w-full">
          <CardHeader>
            <CardTitle className="text-2xl text-center font-bold">Sign In</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <Button className="w-full bg-[#4285F4] text-white" type="button">
              <ChromeIcon className="w-4 h-4 mr-2" />
              Sign in with Google
            </Button>
            <div className="space-y-2">
              <Label htmlFor="email">Email</Label>
              <Input id="email" required type="email" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="password">Password</Label>
              <Input id="password" required type="password" />
            </div>
            <Button className="w-full" type="submit">
              Sign in
            </Button>
          </CardContent>
          <CardFooter className="text-center">
            <p className="text-gray-500">
              Don't have an account?{" "}
              <Link className="underline" href="#">
                Sign Up
              </Link>
            </p>
          </CardFooter>
        </Card>
      </div>
    </div>)
  );
}


function ChromeIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="12" cy="12" r="10" />
      <circle cx="12" cy="12" r="4" />
      <line x1="21.17" x2="12" y1="8" y2="8" />
      <line x1="3.95" x2="8.54" y1="6.06" y2="14" />
      <line x1="10.88" x2="15.46" y1="21.94" y2="14" />
    </svg>)
  );
}
