/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/VWE7H35y677
 */
import { Badge } from "@/components/ui/badge"

export function steps() {
  return (
    (<section key="1" className="w-full py-12 md:py-24 lg:py-32">
      <div
        className="container grid items-center justify-center gap-4 px-4 text-center md:px-6 lg:gap-10">
        <div className="space-y-3">
          <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Our Process</h2>
          <p
            className="mx-auto max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
            We follow a simple three-step process.
          </p>
        </div>
        <div className="flex w-full justify-evenly divide-x divide-gray-200">
          <div className="flex items-center justify-center p-4 sm:p-8">
            <Badge className="items-center" variant="outline">
              <CheckIcon className="h-3.5 w-3.5 -translate-x-1" />
              Step 1
            </Badge>
          </div>
          <div className="flex items-center justify-center p-4 sm:p-8">
            <ArrowRightIcon className="h-3.5 w-3.5 -translate-x-1" />
          </div>
          <div className="flex items-center justify-center p-4 sm:p-8">
            <Badge className="items-center" variant="outline">
              <CheckIcon className="h-3.5 w-3.5 -translate-x-1" />
              Step 2
            </Badge>
          </div>
          <div className="flex items-center justify-center p-4 sm:p-8">
            <ArrowRightIcon className="h-3.5 w-3.5 -translate-x-1" />
          </div>
          <div className="flex items-center justify-center p-4 sm:p-8">
            <Badge className="items-center" variant="outline">
              <CheckIcon className="h-3.5 w-3.5 -translate-x-1" />
              Step 3
            </Badge>
          </div>
        </div>
      </div>
    </section>)
  );
}


function CheckIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <polyline points="20 6 9 17 4 12" />
    </svg>)
  );
}


function ArrowRightIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M5 12h14" />
      <path d="m12 5 7 7-7 7" />
    </svg>)
  );
}
